### ISSUE TITLE
Errors in example translations

### ISSUE THREAD

**Issue by Evelf** [Alaanor/kimchi-grammar#99]
https://github.com/Alaanor/kimchi-grammar/blob/6c07c57ea7cade78035491442668f9fbfd9ac066/point/%EB%8B%A4%EC%8B%9C%ED%94%BC_%ED%95%98%EB%8B%A4.yaml#L12

> sentence: 비가 너무 많이 와서 물에 <f>잠기다시피 했어요</f>.
> translated: May I sit here?

The translation for this example sentence is incorrect (should be "It rained so much that I almost flooded it." or something similar)

Next example translation is also incorrect:

> sentence: 그 여자는 삼겹살을 주식으로 <f>하다시피 해요</f>.
> translated: Do you mind if I open the window?

**Comment by Alaanor** [comment]
Oof, I don't know what happened there but good catch, I'll write a fix for it tomorrow, thanks for spotting it ! :pray:

**Comment by Evelf** [comment]
I plan to mix the notes in this repo with my own study notes, so I'll review most of the content I guess.
If I ever catch other small errors, do you prefer me to open a bug or a PR?

**Comment by Alaanor** [comment]
If you can do a PR, then sure ! For this one, don't bother about it, I'll do it
